# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_desc_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='content',
        ),
    ]
