# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-03-04 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_remove_goods_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goods',
            old_name='desc_detail',
            new_name='content',
        ),
    ]
